server:
  port: 8080

security:
  signing-key: NXXvqCajSQhQaq5FpttOFzwqXdVurA4OeC1xHyaIaYXvN9Qkheg7HAuvNMx2Ndz
  realm-name: Spring Boot JWT Realm

resource-server:
  resourceId: testjwtresource

spring:
  datasource:
    url: jdbc:mysql://192.168.0.179:3306/authDB?createDatabaseIfNotExist=true
    username: root
    password: mysql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace